#!/bin/bash
#bash script to make EPS files of figures
#makes them selfcontained for easy transport.
#then uses ps2eps to put a bounding box on them.  

for j in twoplanes_wave eff_atom eff_2wall
 do
#Dans version
  # ps2eps -l -f $i
  # ps2pdf -dAutoRotatePages=/None -DEPSCrop ${i%.ps}.eps
  # rm -f ${i%.ps}.eps

 ps2pdf -P $j.ps $j.1.pdf
 pdfcrop  $j.1.pdf $j.pdf
 rm $j.1.pdf
done


